### ISSUE TITLE
Add ADDITIONAL_VERIFICATION_CALL_TIME to constants

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/golem-messages#267]
According to https://github.com/golemfactory/concent/issues/828 Concent should use default `ADDITIONAL_VERIFICATION_CALL_TIME` from Golem-messages constant. Please add it there.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/160650744

**Comment by lukasz-glen** [comment]
We define
AVCT = FAT + 3*CMT
It is because FAT + 2*CMT is needed for possible third use case.
Please verify it in code because it is so in the analytic documentation and I am not sure if it complies with code: AVCT begins at the end of SVT (not at the end of third use case which is SVT + FAT + 2*CMT).
