### ISSUE TITLE
v2.19+ nested `TaskToCompute._ethsig` doesn't survive serialization+deserialization of the parent

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/golem-messages#295]
Problem exists in `golem_messages` versions `v2.19+` and doesn't exist in `v2.18`

To reproduce:
```
In [1]: from golem_messages import ECCx

In [2]: from golem_messages.message.tasks import ReportComputedTask

In [3]: from golem_messages.factories.tasks import ReportComputedTaskFactory

In [4]: rct = ReportComputedTaskFactory()

In [5]: ecc = ECCx(None)

In [6]: rcts = rct.serialize(sign_as=ecc.raw_privkey)

In [7]: rctd = ReportComputedTask.deserialize(rcts, None)

In [8]: rctd.task_to_compute._ethsig

In [9]: type(rctd.task_to_compute._ethsig)
Out[9]: NoneType
```

```python
from golem_messages import ECCx
from golem_messages.message.tasks import ReportComputedTask
from golem_messages.factories.tasks import ReportComputedTaskFactory
rct = ReportComputedTaskFactory()
ecc = ECCx(None)
rcts = rct.serialize(sign_as=ecc.raw_privkey)
rctd = ReportComputedTask.deserialize(rcts, None)
rctd.task_to_compute.ethsig
type(rctd.task_to_compute.ethsig)
```

**Comment by rwrzesien** [comment]
The problem seems to be related with the fact that `_ethsign` is defined as slot but treated in a special way. Instead of being serialized along with other slots, it is being added to serialized slots, but the reversed operation which is implemented in `TaskToCompute.deserialize_with_header` is not being called during nested `TaskToCompute` as slot deserialization.
Possible solutions:
1. Treat `_ethsign` as regular slot.
2. Add `if` condition somewhere in `Message.deserialize_message_single` method that for `TaskToCompute` `deserialize_with_header` should be called.

**Comment by shadeofblue** [comment]
so yeah, just implement #247

**Comment by jiivan** [comment]
Fixed by accident
